/* =====================================================
PINESPHERE ERP
Module      : Frontend Platform
Component   : Prisma Config
Purpose     : Provides Prisma Config frontend logic and shared types
Author      : Pinesphere Development Team
Last Updated: Auto Generated
===================================================== */

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/* =====================================================
   SECTION: IMPORTS
   PURPOSE:
   This section loads external libraries, framework tools, and local helpers.
   Keeping imports together makes dependencies easy to review.
===================================================== */

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
